services:
  app:
    build: . # buildear la imagen al momento de lanzar
    # image: alete89/docker-example #usar una imagen local o remota
    environment:
      MONGO_URL: "mongodb://mongo/test"
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    command: mongod --noauth --bind_ip_all
